baseurl = "/"
languageCode = "es-CL"
languageLang = "es"
title = "Imágenes En Conflicto"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
